---
title: "Three band image clustering"
author: "Rian Botes"
date: "17/04/2021"
output: html_document
---

```{r setup, include=FALSE}
library(jpeg)
library(gdata)
library(grid)
library(png)
wd = getwd()
setwd(wd)
img1 = readJPEG('a.jpg')
img8 = readJPEG('g.jpg')

dim(img8)  #will have to compress im8 first!

kimage_clus = function(band_mat, k, let){
  q = nrow(band_mat) #rows in image
  w = ncol(band_mat) #columns in image
  r = matrix(band_mat[,,1], nrow = q*w, ncol = 1)
  g = matrix(band_mat[,,2], nrow = q*w, ncol = 1)
  b = matrix(band_mat[,,3], nrow = q*w, ncol = 1)
  clus_mat = cbind(r, g, b)
  
  clus = kmeans(clus_mat, k, iter.max = 20)
  res = fitted(clus) #These are the results from the clustering, indicating which pixel belongs to which cluster
  r_pc = matrix(res[, 1], nrow = q, ncol = w) #colour_pc = colour_postcluster
  g_pc = matrix(res[, 2], nrow = q, ncol = w)
  b_pc = matrix(res[, 2], nrow = q, ncol = w)
  
  col <- rgb(r_pc, g_pc, b_pc)
  dim(col) <- dim(r_pc)
  
  ar_image <- array(c(r_pc, g_pc, b_pc), c(q, w, 3)) 
  writePNG(ar_image, target = paste0(let,k, ".png"), dpi = NULL, asp = NULL, text = NULL, metadata = NULL)
  reduction = (file.size(paste0(let,".jpg")) - file.size(paste0(let,k, ".png")))/10^6
  let
  reduction
  return(reduction)
}

#t = kimage_clus(img1, 2, "b")
#t 


```

Now, we will output the clustered images for each image in a loop

```{r}
n_imgs = 9 
ks = c(2, 3, 5, 10, 100)
start = Sys.time()
img_let = c("a", "b", "c", "d", "e", "f", "g", "h", "i")
reductions = matrix(0, nrow = length(ks)*length(img_let), ncol = 3)
counter = 0
for (i in 1:n_imgs){
  counter = counter + 1
  img_i = readJPEG(paste0(img_let[i],'.jpg'))
  for (k in ks){
    t = img_let[i]
    #print(t)
    #print(k)
    result = kimage_clus(img_i, k, img_let[i])
    reductions[counter, 1] = img_let[i]
    reductions[counter, 2] = k
    reductions[counter, 3] = result
  }
  progress = 100*(i/n_imgs)
  cat(progress,"%")
}
end = sys.time()
duration = end-start
duration

reductions


```

